# Generated by Django 2.1.3 on 2018-11-15 21:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.date.today, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='first_name',
            field=models.CharField(default='first_name', max_length=60),
        ),
        migrations.AddField(
            model_name='business',
            name='last_name',
            field=models.CharField(default='last_name', max_length=60),
        ),
        migrations.AddField(
            model_name='business',
            name='password',
            field=models.CharField(default='password', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='business',
            name='phone_number',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='business',
            name='username',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
