# Generated by Django 2.1.3 on 2018-11-27 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0004_auto_20181115_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=15)),
                ('business_id', models.CharField(max_length=100)),
                ('street_home_address', models.CharField(max_length=100)),
                ('apt_home_address', models.CharField(blank=True, max_length=100)),
                ('city_home_address', models.CharField(max_length=100)),
                ('state_home_address', models.CharField(max_length=100)),
                ('country_home_address', models.CharField(max_length=100)),
                ('zip_home_address', models.CharField(max_length=15)),
            ],
            options={
                'ordering': ('phone_number',),
            },
        ),
    ]
