# Generated by Django 2.1.3 on 2018-11-27 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0005_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='business_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1.Business'),
        ),
    ]
